version: '3.1'
services:
  mongodb:
    image: mongo
    restart: always
    networks: 
      - fintech
      - ecommerce
    volume: 
      - mongo-data:/data/db
    environment:
      - MONGO_DB_USERNAME=devdb
      - MONGO_DB_PASSWORD=dev@123
  springapp:
    image: ayodejicarew/spring-boot-mongo
    restart: always
    depends_on:
      - mongodb
    networks: 
      - fintech
      - ecommerce
    ports:
      - 7000:8080
    environment:
      - MONGO_DB_HOSTNAME=mongodb
      - MONGO_DB_USERNAME=devdb
      - MONGO_DB_PASSWORD=dev@123
volumes:
  mongo-data:
    driver: local
  ebs-data:
    driver: rexray/ebs
networks:
  fintech:
    driver:bridge
  ecommerce:

