apiVersion: v1   
kind: Pod 
metadata:   
  name: myapp    
  namespace: dev  
  labels:
    app: myapp 
spec:
  containers:
  - name: webapp 
    image: mylandmarktech/spring-boot-mongo  
    ports:
    - containerPort: 8080