#ReplicationController 

apiVersion: v1   
kind: ReplicationController    
metadata:
  name: apprc  
spec:
  selector: 
    app: webapp
  replicas: 3      
  template:
    metadata:
      name: app   
      labels:
        app: webapp
    spec:
      containers:
      - name: appc 
        image: mylandmarktech/hello
        ports:
        - containerPort: 80  
---
apiVersion: v1 
kind: Service
metadata:
  name: webappsvc
spec:
  type: NodePort 
  selector:
    app: webapp
  ports:
  - targetPort: 80
    port: 80
